//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyTable
    {
        public int MoneyId { get; set; }
        public double BidPrice { get; set; }
        public decimal SellingPrice { get; set; }
        public Nullable<System.DateTime> CreatedBy { get; set; }
    }
}
